<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Accepted' => '通过',
    'Are you sure you want to Accepted this comment?' => '你确定要接受该评论？',
    'Batch Deletion' => '批量删除',
    'Comment has been confirmed' => '评论已审核',
    'Created At' => '创建时间',
    'Manage Comment' => '评论管理',
    'Parent Content' => '父评论',
    'Pending' => '待审',
    'Content' => '内容',
    'One minute only comment once.' => '一分钟内只能评论一次',
    'Status' => '状态',
    'Submit Comment' => '提交评论',
    'You can not submit the same comment.' => '请不要重复提交',
    'source Id' => '源ID',
    'source Type' => '源模型',
];
